version: "3.7"

services:
    db:
        build:
            context: ./mysql-db/
            dockerfile: Dockerfile
        image: 10hlab-mysql-db:v1
        container_name: 10hlab-db
        ports:
            -   3307:3306
        env_file:
            -   ./mysql-db/.env

    soap:
        build:
            context: ./php-soapservice/
            dockerfile: Dockerfile
        image: 10hlab-soap-server:v1
        container_name: 10hlab-php
        command: ["wait.sh", "php", "-S", "0.0.0.0:7000"]
        volumes:
            -   ./php-soapservice:/opt/app
            -   php_vendor:/opt/app/vendor
        ports:
            -   7000:7000
        links:
            -   db:10hlab-db
        depends_on:
            -   db

    api:
        build:
            context: ./flask-api/
            dockerfile: Dockerfile
        image: 10hlab-flask-api:v1
        container_name: 10hlab-api
        command: ["flask", "run", "--host", "0.0.0.0"]
        volumes:
            -   ./flask-api:/opt/api
        ports:
            -   5000:5000
        links:
            -   soap:10hlab-php
        depends_on:
            -   soap

    web:
        build:
            context: ./react-frontend/
            dockerfile: Dockerfile
        image: 10hlab-react-app:v1
        container_name: 10hlab-web
        command: ["yarn", "start"]
        volumes:
            -   ./react-frontend:/opt/web
            -   react_modules:/opt/web/node_modules
        ports:
            -   3000:3000
        links:
            -   api:10hlab-api
        depends_on:
            -   api

networks:
    default:
        driver: bridge
        name: 10hlab-net

volumes:
    php_vendor:
    react_modules:
