version: '3.7'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - ./migration:/docker-entrypoint-initdb.d
